extends:
    - ./base.yml

rules:
    #===========================================================================
    # TSLint
    #===========================================================================
    #---------------------------------------------------------------------------
    ## Functionality
    #---------------------------------------------------------------------------
    no-implicit-dependencies: false

    no-shadowed-variable: false

    no-submodule-imports: false

    no-this-assignment:
        - true
        -
            allow-destructuring: false
            allowed-names:
                - "^vm$"

    no-unsafe-any: false

    #---------------------------------------------------------------------------
    ## Maintainability
    #---------------------------------------------------------------------------
    no-require-imports: false

    #---------------------------------------------------------------------------
    ## Style
    #---------------------------------------------------------------------------
    interface-name:
        - true
        - always-prefix
