rules:
    #===========================================================================
    # TSLint
    #===========================================================================
    #---------------------------------------------------------------------------
    ## TypeScript-specific
    #---------------------------------------------------------------------------
    adjacent-overload-signatures: false

    ban-types: false

    member-access:
        - true
        - no-public

    member-ordering:
        - true
        -
            order:
                # Instance fields
                - public-instance-field
                - protected-instance-field
                - private-instance-field

                # Static fields
                - public-static-field
                - protected-static-field
                - private-static-field

                # Constructor
                - public-constructor
                - protected-constructor
                - private-constructor

                # Instance methods
                - public-instance-method
                - protected-instance-method
                - private-instance-method

                # Static methods
                - public-static-method
                - protected-static-method
                - private-static-method

    no-any: false

    no-empty-interface: false

    no-import-side-effect: false

    no-inferrable-types:
        - true
        - ignore-params
        - ignore-properties

    no-internal-module: true

    no-magic-numbers: true

    no-namespace:
        - true
        - allow-declarations

    no-non-null-assertion: false

    no-parameter-reassignment: true

    no-reference: true

    no-unnecessary-type-assertion: true

    no-var-requires: true

    only-arrow-functions: false

    prefer-for-of: false

    promise-function-async: false

    typedef: false

    typedef-whitespace:
        - true
        -
            call-signature:       nospace
            index-signature:      nospace
            parameter:            nospace
            property-declaration: nospace
            variable-declaration: nospace
        -
            call-signature:       space
            index-signature:      space
            parameter:            space
            property-declaration: space
            variable-declaration: space

    unified-signatures: true

    #---------------------------------------------------------------------------
    ## Functionality
    #---------------------------------------------------------------------------
    await-promise:
        - true
        - Thenable
        - IPromise

    ban-comma-operator: true

    ban: false

    curly: true

    forin: true

    import-blacklist: false

    label-position: true

    no-arg: true

    no-bitwise: false

    no-conditional-assignment: true

    no-console: false

    no-construct: true

    no-debugger: true

    no-duplicate-super: true

    no-duplicate-switch-case: true

    no-duplicate-variable:
        - true
        - check-parameters

    no-dynamic-delete: false

    no-empty: true

    no-eval: true

    no-floating-promises: true

    no-for-in-array: true

    no-implicit-dependencies: true

    no-inferred-empty-object-type: true

    no-invalid-template-strings: true

    no-invalid-this: true

    no-misused-new: false

    no-null-keyword: false

    no-object-literal-type-assertion: false

    no-return-await: true

    no-shadowed-variable:
        - true
        - temporalDeadZone: true

    no-sparse-arrays: true

    no-string-literal: true

    no-string-throw: true

    no-submodule-imports: true

    no-switch-case-fall-through: true

    no-this-assignment: true

    no-unbound-method: true

    no-unnecessary-class:
        - true
        - allow-empty-class: true

    no-unsafe-any: true

    no-unsafe-finally: true

    no-unused-expression: true

    no-unused-variable: true

    no-use-before-declare: true

    no-var-keyword: true

    no-void-expression: false

    prefer-conditional-expression: true

    prefer-object-spread: true

    restrict-plus-operands: false

    strict-boolean-expressions: false

    strict-type-predicates: false

    switch-default: true

    triple-equals: true

    # DEPRECATED: typeof-compare: true

    use-default-type-parameter: true

    use-isnan: true

    #---------------------------------------------------------------------------
    ## Maintainability
    #---------------------------------------------------------------------------
    cyclomatic-complexity: true

    deprecation: true

    eofline: true

    indent:
        - true
        - spaces
        - 2

    linebreak-style:
        - true
        - LF

    max-classes-per-file:
        - true
        - 1

    max-file-line-count: false

    max-line-length:
        - true
        -
            limit: 80
            ignore-pattern: "^import |^export |^}\\s+from\\s+['\"]|\\/\\/"

    no-default-export: false

    no-duplicate-imports: true

    no-mergeable-namespace: true

    no-require-imports: true

    object-literal-sort-keys: false

    prefer-const: true

    prefer-readonly: false

    trailing-comma:
        - true
        -
            multiline: never
            singleline: never

    #---------------------------------------------------------------------------
    ## Style
    #---------------------------------------------------------------------------
    align:
        - true
        - parameters
        # - arguments
        - statements
        - members
        - elements

    array-type:
        - true
        - array-simple

    arrow-parens: true

    arrow-return-shorthand:
        - true
        - multiline

    binary-expression-operand-order: true

    callable-types: false

    class-name: true

    comment-format:
        - true
        - check-space
        # - check-uppercase

    completed-docs: false

    encoding: true

    file-header: false

    import-spacing: false # Because it does not work with more than 1 space

    interface-name:
        - true
        - never-prefix

    interface-over-type-literal: true

    jsdoc-format:
        - true
        - check-multiline-start

    match-default-export-name: false

    newline-before-return: true

    newline-per-chained-call: true

    new-parens: true

    no-angle-bracket-type-assertion: true

    no-boolean-literal-compare: true

    no-consecutive-blank-lines:
        - true
        - 2

    no-irregular-whitespace: true

    no-parameter-properties: false

    no-redundant-jsdoc: false

    no-reference-import: true

    no-trailing-whitespace: true

    no-unnecessary-callback-wrapper: true

    no-unnecessary-initializer: true

    no-unnecessary-qualifier: true

    number-literal-format: true

    object-literal-key-quotes:
        - true
        - as-needed

    object-literal-shorthand: true

    one-line:
        - true
        - check-catch
        - check-finally
        - check-else
        - check-open-brace
        - check-whitespace

    one-variable-per-declaration:
        - true
        - ignore-for-loop

    ordered-imports:
        - true
        -
            grouped-imports: true
            import-sources-order: lowercase-last
            named-imports-order: lowercase-last
            module-source-path: full

    prefer-function-over-method: true

    prefer-method-signature: true

    prefer-switch:
        - true
        - min-cases: 3

    prefer-template:
        - true
        - allow-single-concat

    quotemark:
        - true
        - single
        - jsx-single
        - avoid-template

    return-undefined: true

    semicolon:
        - true
        - always
        - strict-bound-class-methods

    space-before-function-paren:
        - true
        -
            anonymous: always
            named: never
            asyncArrow: always
            method: never
            constructor: never

    space-within-parens: 0

    switch-final-break:
        - true
        - always

    type-literal-delimiter: true

    variable-name:
        - true
        - check-format
        - allow-leading-underscore
        # - allow-trailing-underscore
        - allow-pascal-case
        - allow-snake-case
        - ban-keywords

    whitespace:
        - true
        - check-branch
        - check-decl
        - check-operator
        - check-module
        - check-separator
        - check-rest-spread
        - check-type
        - check-typecast
        - check-type-operator
        - check-preblock

    #===========================================================================
    # tslint-eslint-rules
    #===========================================================================
    #---------------------------------------------------------------------------
    ## Possible Errors
    #---------------------------------------------------------------------------
    no-constant-condition:
        - true
        - checkLoops: false

    no-control-regex: false

    no-duplicate-case: true

    no-empty-character-class: true

    no-ex-assign: true

    no-extra-boolean-cast: true

    no-extra-semi: true

    no-inner-declarations:
        - true
        - both

    no-invalid-regexp: true

    ter-no-irregular-whitespace: true

    no-regex-spaces: true

    ter-no-sparse-arrays: true

    no-unexpected-multiline: true

    valid-jsdoc:
        - true
        -
            prefer:
                return: return
            requireReturn: true
            requireParamType: true
            requireReturnType: true
            requireParamDescription: false
            requireReturnDescription: false

    valid-typeof: true

    #---------------------------------------------------------------------------
    ## Best Practices
    #---------------------------------------------------------------------------
    no-multi-spaces: false

    # DOES_NOT_EXIST: ter-no-proto: true

    # DOES_NOT_EXIST: ter-no-script-url: true

    # DOES_NOT_EXIST: ter-no-self-compare: true

    #---------------------------------------------------------------------------
    ## Node.js and CommonJS
    #---------------------------------------------------------------------------
    handle-callback-err:
        - true
        - err

    #---------------------------------------------------------------------------
    ## Stylistic Issues
    #---------------------------------------------------------------------------
    array-bracket-spacing:
        - true
        - never

    block-spacing:
        - true
        - always

    brace-style:
        - true
        - 1tbs
        - allowSingleLine: true

    ter-computed-property-spacing:
        - true
        - never

    ter-func-call-spacing:
        - true
        - never
        - allowNewlines: false

    ter-indent:
        - true
        - 2
        -
            SwitchCase: 1
            VariableDeclarator:
                var: 2
                let: 2
                const: 3
            outerIIFEBody: 1
            MemberExpression: 1
            FunctionDeclaration:
                parameters: 1
                body: 1
            FunctionExpression:
                parameters: 1
                body: 1
            CallExpression:
                arguments: 1

    ter-max-len: false

    ter-newline-after-var:
        - true
        - always

    ter-no-mixed-spaces-and-tabs:
        - true
        -
            type: spaces
            smartTabs: false

    object-curly-spacing:
        - true
        - always

    ter-padded-blocks:
        - true
        - never

    sort-imports: false

    space-in-parens:
        - true
        - never

    ter-no-tabs: true

    #---------------------------------------------------------------------------
    ## Stylistic Issues
    #---------------------------------------------------------------------------
    ter-arrow-body-style:
        - true
        - as-needed
        - requireReturnForObjectLiteral: false

    ter-arrow-parens:
        - true
        - always
        - requireForBlockBody: true

    ter-arrow-spacing:
        - true
        -
            before: true
            after: true

    ter-prefer-arrow-callback:
        - true
        -
            allowNamedFunctions: true
            allowUnboundThis: true
